Get completed items
Doist/todoist-api-python pull request #90
Opened 2023-01-23 22:48 UTC by jkawamoto

It's useful if the client can get completed tasks. This PR implements `get_completed_items` that calls [Get completed items](https://developer.todoist.com/sync/v9/#get-completed-items) API.

Since it looks like models are migrating to use `dataclass` instead of `attrs` (#85), this PR also uses `dataclass` to define models.

Related to #32 and #56.

2023-01-24 02:37 UTC, theptrk commented
This would be very useful! 

I hope this library isn't REST API only since the Sync API still has useful endpoints such as activity logs.

2023-08-09 11:56 UTC, lefcha requested changes
The PR looks great, apart from the one comment I had. If it's addressed we can merge it. Thanks!

2023-08-09 11:56 UTC, lefcha commented on todoist_api_python/models.py
> +    """The ID of the task."""
Could you remove all the docstrings from this point and below, so the code looks the same as the rest of the file?

These dataclasses are mainly for input validation, and the descriptions of the properties are in the [Todoist API doc](https://developer.todoist.com) so we don't need to duplicate them here.

2023-08-10 20:33 UTC, jkawamoto commented
Thank you for your review. I removed the docstrings and rebased this branch onto the latest main.

2023-08-15 15:04 UTC, lefcha approved these changes

2023-08-15 15:05 UTC, merged

2023-08-15 15:36 UTC, theptrk commented
thanks for merging this 🎉

2023-08-15 15:58 UTC, brunorosilva commented
Great! @lefcha, I'm working on #96 which will also use the Sync API, will this be a problem in the future? The doc seems clear about not using calls to the Sync API.

2023-08-16 07:23 UTC, lefcha commented
@brunorosilva It's OK to use auxiliary API endpoints from the Sync API in this library. What we don't want is to use the `sync` command itself. Unfortunately the archiving functionality is part of the `sync` command, so a PR would not be accepted.

You would need to wait for us to implement this in the REST API. CC @PotHix

2023-08-16 13:09 UTC, brunorosilva commented
OK @lefcha , thanks for the info.